### ISSUE TITLE
Request to make an.exe version or portable version?

### ISSUE THREAD

**Issue by aimarxjg** [MNeMoNiCuZ/Trimage#8]
Thank you for your work and selfless sharing❤️, can you add the function of reading picture PROMPT? That's more convenient. Something like this    https://github.com/receyuki/stable-diffusion-prompt-reader

**Comment by MNeMoNiCuZ** [comment]
Try this:
https://github.com/MNeMoNiCuZ/ImageSorting/releases/tag/release

I think I managed to compile it to an .exe

It should be portable.

**Comment by aimarxjg** [comment]
Thank you very much❤️

**Comment by MNeMoNiCuZ** [comment]
Did it not work?

**Comment by MNeMoNiCuZ** [comment]
Oh, you renamed the issue instead of creating a new one XD

Hmm, maybe, I'll have to think a bit about it.
It's not a bad feature request, it's certainly possible and should be easy to do.

**Comment by MNeMoNiCuZ** [comment]
Opened a new issue to track the feature requests separately.
https://github.com/MNeMoNiCuZ/ImageSorting/issues/9
